//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string COLLISION_IMPACT = "collision_impact";
        
        public const string ENGINE_VIBRATION = "engine_vibration";
        
        public const string LANDING_IMPACT = "landing_impact";
        
        public const string BRAKE_FEEDBACK = "brake_feedback";
        
        public const string UI_BUTTON_CLICK = "ui_button_click";
        
        public const string CAR_ACCIDENT = "car_accident";
        
        public const string JUMP_LIFTOFF = "jump_liftoff";
    }
}
